import type { ScriptIcon } from './script-contract'

export const SCRIPT_ICON_OPTIONS: { id: ScriptIcon; label: string }[] = [
  { id: 'globe', label: '地球' },
  { id: 'download-cloud', label: '下载' },
  { id: 'upload', label: '上传' },
  { id: 'app-window', label: '窗口' },
  { id: 'monitor', label: '监控' },
  { id: 'folder-sync', label: '同步' },
  { id: 'cloud', label: '云端' },
  { id: 'server', label: '服务器' },
  { id: 'database', label: '数据库' },
  { id: 'terminal', label: '终端' },
  { id: 'code', label: '代码' },
  { id: 'bot', label: '机器人' },
  { id: 'workflow', label: '流程' },
  { id: 'zap', label: '自动化' },
  { id: 'cpu', label: '系统' },
  { id: 'settings', label: '设置' },
  { id: 'wrench', label: '工具' },
  { id: 'mail', label: '邮件' },
  { id: 'send', label: '发送' },
  { id: 'bell', label: '通知' },
  { id: 'key-round', label: '密钥' },
  { id: 'shield', label: '安全' },
  { id: 'lock', label: '锁定' },
  { id: 'search', label: '搜索' },
  { id: 'link', label: '链接' },
  { id: 'clock', label: '定时' },
  { id: 'calendar', label: '日历' },
  { id: 'file-text', label: '文档' },
  { id: 'table', label: '表格' },
  { id: 'file-spreadsheet', label: '电子表格' },
  { id: 'image', label: '图片' },
  { id: 'camera', label: '截图' },
  { id: 'bar-chart', label: '图表' },
  { id: 'map', label: '地图' },
  { id: 'home', label: '首页' },
  { id: 'shopping-cart', label: '电商' },
  { id: 'package', label: '软件包' }
]
